### ISSUE TITLE
Time to resolve for parallel_scrape_songs function?

### ISSUE THREAD

**Issue by rmjutras** [rmjutras/EUROBOT#3] opened 2016-02-02 21:42 UTC
So I wanted to have the SongObject results in my workplace pre-pickling so I ran:
`urls = get_song_urls()
results = parallel_scrape_songs(urls)`
Any idea on how long this should take? For one url it was taking >30min.

Alternatively, I have never worked with pickled data. Can you write a short how to on unpickling properly? I tried just opening and unpickling the file but it wasn't working.

**Comment by rmjutras** [comment] 2016-02-03 01:30
Ah the reason I am having trouble with 
`songs = pickle.load( open( "C:\Users\Data\Desktop\Renee\EUROBOT\pickled.bin", "rb" ) )`
is that this pickle is not Python 2 compatible. 
Use `pickle.dump(your_object, your_file, protocol=2)` to make a pickled file compatible with Python 2.

**Comment by InvncibiltyCloak** [comment] 2016-02-03 02:52
I removed the pickle files from the git repo for exactly this reason. The intent is for people to generate it on their own. Running `python LyricScraper.py` will regenerate it. 

Also, any way I can convince you to switch to Python 3? Its the future, you know.

**Comment by InvncibiltyCloak** [comment] 2016-02-03 02:56
As far as `parallel_scrape_songs` taking excessively long, I am not sure. The whole scraping process does take a while (~10 minutes), because there are 4000+ songs. It should report percent completion in the console. If you aren't getting that, then something is wrong.

**Comment by rmjutras** [comment] 2016-02-03 19:42
Yeah it definitely was taking >10 hours for me. Not sure why. And I can't switch to 3; 2.7 is the accepted standard for data science packages & our company dev work.

**Comment by InvncibiltyCloak** [comment] 2016-02-03 22:09
With the latest version of master, I have no problems running it in 2.7.10, assuming all dependencies are installed. I just tried it in Windows 2.7 and got a hang because BeautifulSoup was not installed (which may be a bug in the import mechanism). When you kill python with Ctrl-C while running, it gives a traceback which shows where it was within the program. This might help me debug.  Or a screenshot. Or something to work with. All I can do is guess right now.

Note that it is certainly possible to have both 2 and 3 installed. I have both 2 and 3 in Linux and Windows. There is likely an option in your IDE to choose between the two, once installed.

**Comment by InvncibiltyCloak** [comment] 2016-02-04 01:08
I just committed a new version which uses the Requests library. It increases the cross-platformness and makes scraping WAAAAYYY faster. I can complete a scrape in just 30 seconds, on the not-the-best internet here. Confirmed working in Windows w/ Python 2.7.

**Comment by rmjutras** [comment] 2016-02-09 05:01
sugoi checking it out

**Closed as completed** 2016-02-09 05:11 UTC
Labels: help wanted
